### PR TITLE
Autonomous added timer

### PR DESCRIPTION
**Pull request by the-emerald**
May need to add a private class to allow the timer to exist in the code. Also added the strength of the sparks in autonomous. The robot arrives to the line in 7-8 seconds.

### CODE REVIEW

**Comment by the-emerald** [comment]
@imvektor There are multiple syntax errors with this.
```
Error:(67, 5) Cannot resolve symbol 'm_timer'
Error:(68, 5) Cannot resolve symbol 'm_timer'
Error:(79, 5) Cannot resolve symbol 'right1Back'
Error:(80, 8) Cannot resolve symbol 'm_timer'
Error:(81, 7) Cannot resolve symbol 'robot'
```
Please fix these errors with your code before I can sign off this PR.
There are problems with indentation - 2 spaces please.

**Comment by VF-02** [comment]
Lmao I know, because as I had said before, I need to add the variables

**Comment by the-emerald** [comment]
Please fix those issues and I'll do the code cleanup.

**Comment by VF-02** [comment]
Alright

**Comment by the-emerald** [comment]
@Ozhav is this good for merge?

**Pull request closed without merging**
